name: Robot Penjaga Kode

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Sapa Programmer
        run: echo "Halo! Robot CI sedang mengecek file README.md kamu."
